### ISSUE TITLE
Feature Request: Change namespace property in sensu_check from string to array

### ISSUE THREAD

**Issue by csoleimani** [sensu/sensu-puppet#1125]
And automatically create the check in every namespace in the array. I'm currently doing this:
```
$namespaces = ['test1', 'test2']
  $namespaces.each |$namespace| {
  sensu_check {"${namespace}-check-hardware":
      command       => "${ruby} ${install_path}/check-hardware-fail.rb -L emerg, alert, crit",
      handlers      => lookup('page::for::production::only'),
      interval      => 60,
      annotations   => {
        'fatigue_check/occurrences' => '5',
      },
      subscriptions => 'hardware',
      namespace     => $namespace,
    }
  }
```

It would be nice if we could do this instead:

```

  sensu_check {'check-hardware':
    command       => "${ruby} ${install_path}/check-hardware-fail.rb -L emerg, alert, crit",
    handlers      => lookup('page::for::production::only'),
    interval      => 60,
    annotations   => {
      'fatigue_check/occurrences' => '5',
    },
    subscriptions => 'hardware',
    namespace     =>['test1', 'test2'],
    }
  }
```

Maybe rename namespace parameter to namespaces if this happens?

**Comment by treydock** [comment]
A few comments.

First I'd prefer to add a new property called `namespaces` that would accept an array of namespaces. Most if not all properties of the types are directly mapped to resource properties in Sensu Go so changing `namespace` to be something different than what Sensu Go accepts is not ideal.

Also your second example wouldn't work because of how we prefetch resources from sensuctl. We look just at name so `test1` or `test2` would be seen and the other ignored if name is the same. I'll have to investigate if there's a way around this. I think this would require us to employ compound titles so the name would be seen as `check-hardware in test1`.

Lastly, because Puppet dictates state there is no way to find the state of a property like `namespaces` because it's not a state in Sensu Go. We'd have to do something like iterate over all checks and group ones with same name and different environments and build `namespaces` property. Not 100% sure that's possible.

**Comment by treydock** [comment]
@csoleimani I am still investigating if something like a `namespaces` property would be possible.  I have fixed several issues with namespace handling in #1126 so now you could do something like this:

```puppet
$namespaces = ['test1', 'test2']
  $namespaces.each |$namespace| {
  sensu_check {"check-hardware in ${namespace}":
      command       => "${ruby} ${install_path}/check-hardware-fail.rb -L emerg, alert, crit",
      handlers      => lookup('page::for::production::only'),
      interval      => 60,
      annotations   => {
        'fatigue_check/occurrences' => '5',
      },
      subscriptions => 'hardware',
    }
  }
```

The main change is the composite name that defines namespace so that in `sensuctl check list` the name would just be `check-hardware`.  Another possible solution is if you define checks in Hiera and want to have all checks in multiple namespaces:

```yaml
sensu_checks:
  check-hardware:
    command: ...
    handlers: ...
sensu_namespaces:
  - test1
  - test2
```

```puppet
$checks = lookup('sensu_checks')
$namespaces = lookup('sensu_namespaces')

$checks.each |$check_name, $check_properties| {
  $namespaces.each |$namespace| {
    sensu_check { "${check_name} in ${namespace}":
      * => $check_properties,
    }
  }
}
```

Similar solution where namespaces are define for a check and not globally:

```yaml
sensu_checks:
  check-hardware:
    command: ...
    handlers: ...
    namespaces:
      - test1
      - test2
```

```puppet
$checks = lookup('sensu_checks')

$checks.each |$check_name, $check_properties| {
  $namespaces = $check_properties['namespaces']
  $properties = delete($check_properties, 'namespaces')
  $namespaces.each |$namespace| {
    sensu_check { "${check_name} in ${namespace}":
      * => $properties,
    }
  }
}
```

**Comment by treydock** [comment]
@csoleimani Adding a `namespaces` property isn't going to work. Changing `namespace` to be an array would not match the property from Sensu Go docs and all Puppet type properties are currently mapped to Sensu Go resource properties.

**Comment by csoleimani** [comment]
The changes you implemented look awesome! I'm going to give them a shot. Thanks a bunch!

**Comment by csoleimani** [comment]
This appears to be working great. Thanks a bunch!

**Comment by ghoneycutt** [comment]
Going to leave this open until we actually merge those changes.
