### ISSUE TITLE
Feature Request - Check if license is installed

### ISSUE THREAD

**Issue by tdmike** [sensu/sensu-puppet#1217]
Hi Guys,

I ran into an issue where my license failed to install when we deployed the sensu cluster. Would it be possible to implement a check when the `license_source` or `license_content` is defined puppet checks if it's installed and if it isn't puppet installs it?

**Comment by ghoneycutt** [comment]
This already happens with the `sensu::backend` class. Were you working with a backend system?

**Comment by tdmike** [comment]
Yes I was, I configured the entire backend through Sensu, somewhere along the line it seems to have failed to install the sensu license. It never corrected this.

**Comment by treydock** [comment]
Currently if `lisence_source` or `license_content` are present Puppet will attempt to install the license but I don't think it will retry upon failure because the Exec is only triggered when the license file is modified. One temporary work around is delete `/etc/sensu/license.json` on the backend host then re-run Puppet.

**Comment by treydock** [comment]
@tdmike #1218 adds better logic around license management and if your license isn't added it will retry the license creation.
