### ISSUE TITLE
Lost the ability to separately define subscriptions

### ISSUE THREAD

**Issue by bodgit** [sensu/sensu-puppet#1222]
## Description of problem

I'm looking to migrate our Sensu install from the old core/1.x way to the new Go codebase. Aside from all of the backend changes I need to make I've realised there's now no way to separately define agent subscriptions.

Previously in the old way, I could just add the following to any class:
```puppet
sensu::subscription { 'blah':
  ensure => present,
}
```
Whereas now, that defined type has disappeared and it seems I need to know all of the subscriptions that will be required/applied to an agent ahead of time to pass them once to the `sensu::agent` class.

## Platform and version information

- Your OS: RHEL 7
- Your Ruby version:
- Your version of Puppet: 5.5.18
- Your version of Sensu: 5.17.2
- Your version of this module: master

## Anything else to add that you think will be helpful?

This is partly the problem of the underlying Sensu Go codebase as it looks like they've removed support for configuration merging, however this could be maybe solved by using a concat type resource to build the agent configuration; a `sensu::subscription` define could then create a concat fragment.

**Comment by treydock** [comment]
This has been raised before and resulted in this Sensu Go issue: https://github.com/sensu/sensu-go/issues/3452.

Some ideas I proposed are here: https://github.com/sensu/sensu-puppet/issues/1183

Using a concat fragment would be impossible to make work because we don't use templates to build the YAML, we build a hash and use `to_yaml` to generate the YAML content.  There would be no way to merge the existing parameters with something like a concat fragment.

I think the only way this could work is if Sensu Go was updated to allow something like `/etc/sensu/agent.d` type configuration directory that is merged with the main `agent.yml`.

**Comment by bodgit** [comment]
Thanks for the pointers @treydock , I did try and see if anyone had raised this issue upstream already but obviously I didn't use the right search terms :wink:

Does the method you proposed in #1183 work now with the latest version of this module? For example:
```puppet
@sensu_entity { $facts['hostname']:
  ...
  subscriptions => ['base'],
}

...

Sensu_entity <| title == $facts['hostname'] |> {
  subscriptions +> ['httpd'],
}
```
If so, does it still work if there are multiple additional subscriptions, i.e. I wanted to add `httpd` and `pgsql` separately, as an example?

Failing that, I'll add my +1 to the upstream issue. Annoyingly, this seems to be the sole blocker to migrating for us as far as I can tell.

**Comment by treydock** [comment]
That method should work. I've only lightly tested it once to verify that it was possible to append subscriptions using `sensu_entity`.

I'd recommend using the API provider to modify the entity which would require following these steps for using `sensu_api` providers:

https://github.com/sensu/sensu-puppet#api-providers

This would avoid having to install `sensuctl` everywhere.  You'd also need to ensure the profile or class including `sensu::agent` defines the `sensu_entity` for that host and then collects it using something like `Sensu_entity <| title == $facts['networking']['hostname'] |>` in case you don't have another collector modifying subscriptions else where.

I think you'll also want to ensure the `sensu_entity` resource comes after `sensu::agent` class or the agent service so that the entity is created automatically by the agent then later modified by `sensu_entity`.

**Comment by treydock** [comment]
@bodgit Check out https://github.com/sensu/sensu-puppet#advanced-agent---subscriptions for docs on new way to define subscriptions.
