### ISSUE TITLE
Setting handlers to undef for a checks does not trigger change in respective json config file.

### ISSUE THREAD

**Issue by mrolli** [sensu/sensu-puppet#414]
After having applied a check to a node with ```handlers => [ 'handler1', 'handlers2' ]``` the respective json config file looks fine:
```
...
  "handlers": [
    "handler1",
    "handler2"
  ],
...
```

But now I'm not able to remove those handlers again. Leaving out the handlers attribute (therefore using the default undef value) on sensu::check does not have an effect. No change to json config file. How am I supposed to remove the handlers previously set? Delete the json on the node works obviously, puppet has to create a new json file.

**Comment by jlambert121** [comment]
What version of puppet are you running?

**Comment by mrolli** [comment]
I'm using puppet-3.8.2-1.el6.noarch, which in turn is using ruby-18.7 on el6.

One possible workaround I found was setting handlers => [], which leads to an empty array in the json file. I hope the default handler is then triggered as when no handlers are configured within the json file.

**Comment by jlambert121** [comment]
Puppet pre-4.0 doesn't have a true undefined and thus the providers aren't able to tell that the parameter is unset.  I believe this should be fixed with 4.x, but know for sure this issue exists in 3.x.

That workaround (or removing the json file and letting puppet re-add it) are the two solutions I know of for this.
