### ISSUE TITLE
Trailing comma issue in config

### ISSUE THREAD

**Issue by nux** [sensu/sensu-puppet#492]
When debugging an issue with uchiwa not connecting to API, I found out that the lack of a trailing slash in redis.json on the last item caused the connection to redis to fail.

{
  "redis": {
    "port": 6379,
    "host": "localhost",
    "reconnect_on_error": false,
    "db": 0,
    "auto_reconnect": "true"
  }
}
vs
{
  "redis": {
    "port": 6379,
    "host": "localhost",
    "reconnect_on_error": false,
    "db": 0,
    "auto_reconnect": "true",
  }
}

This happened after updating packages on Debian (Jessie). Debian was updated from 8.3 to 8.4. Not sure if it's related.

ii  ruby2.1                        2.1.5-2+deb8u2              amd64        Interpreter of object-oriented scripting language Ruby
ii  sensu                          0.23.0-1                    amd64        A monitoring framework that aims to be simple, malleable, and scalable.
ii  uchiwa                         1:0.14.0-1                  amd64        Uchiwa is a simple dashboard for the Sensu monitoring framework.

**Comment by GhostLyrics** [comment]
This is not an issue in sensu-puppet. With a trailing comma the content of the file is not valid JSON and as such not accepted by sensu, causing it to ignore the configuration and go with the default settings. (`grep` for "ignored" in /var/log/sensu/sensu-server.log)

To solve your issue, the host needs to be "127.0.0.1" since resolution is broken in 0.23.0.

**Comment by GhostLyrics** [comment]
Please check https://github.com/sensu/sensu/issues/1209

**Comment by nux** [comment]
Thanks!
