### ISSUE TITLE
DISCUSSION: Move module to vox-pupuli

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu-puppet#585]
I haven't really discussed this with anyone from the org yet, but wanted to get some comments from the users of the module, and also the owners.

Currently, I seem to be the only active maintainer of this module. It is quite difficult to keep up with the PR and issues that come in.

I would like to consider moving the repo under the stewardship of the [https://voxpupuli.org/](Vox Pupuli) which will give us the following benefits:

  - Continued development
  - Multiple people having eyes on pull requests

Obviously I am not the _owner_ of this module, only a maintainer, so this is conditional on the lovely people at sensu being okay with this.

**Comment by madelaney** [comment]
I'd love to see this. As someone who's wantes to use this module, but is waiting on #546 , and would like to add Darwin support. I think allowing more people to help out would be awesome.

**Comment by madAndroid** [comment]
This is a great idea, IMO - there's massive growth and movement on the Vox Pupuli org, and as a collaborator on there, it'd be easier to contribute and get changes merged fairly quickly.

**Comment by GhostLyrics** [comment]
Wholeheartedly agree with allowing more able hands to contribute.

**Comment by portertech** [comment]
:+1:

I am in favour of putting this module in more able hands. I need to investigate how the org operates.

**Comment by jaxxstorm** [comment]
@portertech I can put you in touch with some of the vox-pupuli members if needed.

**Comment by jaxxstorm** [comment]
@portertech @cwjohnston any thoughts here? I'm struggling to find time to maintain this module

**Comment by cwjohnston** [comment]
@jaxxstorm thanks for the ping, presently we are discussing this request internally.

**Comment by GhostLyrics** [comment]
@portertech @cwjohnston Has there been any decision yet? It's kind of getting difficult to recommend this since "sensu is designed to be used with configuration management" and the configuration management side of it getting less attention than necessary for continued use! :(

**Comment by GhostLyrics** [comment]
@portertech @cwjohnston Ping? It's getting harder to recommend sensu due to the puppet module simply stalling and falling behind sensu's core features.

**Comment by cwjohnston** [comment]
@jaxxstorm @GhostLyrics 

We recognize that this project needs dedicated help and we are working to bring in a third-party to provide much needed expert attention. We're choosing to do this instead of moving this module to vox-pupuli because we're working with Puppet to join their [TAP program](https://puppet.com/partners/alliance/technology-alliance-partners).

The level of partnership we're looking to achieve with Puppet requires achieving "supported" status for this module on PuppetForge, which we believe excludes us from relying on the vox-pupuli community for support. 

Naturally we still wholeheartedly welcome contributions from the Puppet community. ❤️ 

We'll be announcing developments around this as events warrant.

**Comment by ghoneycutt** [comment]
My team is now supporting the module. See #673
