### ISSUE TITLE
Remove sensu_check_config

### ISSUE THREAD

**Issue by jeffmccune** [sensu/sensu-puppet#764]
Garrett and I discussed this today.  There is confusion surrounding sensu_check_config, the JSON provider doesn't seem to be well-behaved, the type isn't used anywhere in the module, there isn't any documentation, and the sensu::check type appears to provide all the necessary functionality for checks.

One possible situation is sensu_check_config is able to set keys and values at the same level as "checks" in the target file, whereas sensu::check can only set custom configuration nested under checks['mycheck'].

If it is necessary to add configuration in the top-level map of the JSON files in `conf.d/checks/`, then sensu::check should take a `config` property which is merged together with the `checks` top level key.

**Comment by jeffmccune** [comment]
Related to #759 but is a separate task unrelated to the reference for provider spec testing.

**Comment by cwjohnston** [comment]
> One possible situation is sensu_check_config is able to set keys and values at the same level as "checks" in the target file, whereas sensu::check can only set custom configuration nested under checks['mycheck'].

Sensu is agnostic of custom configuration scopes, so plugins and extensions of all sorts can load Sensu's config on disk and read their settings from arbitrary keys. For example, handler-mailer, handler-mailer-ses and handler-mailer-mailgun plugins in the [sensu-plugins-mailer](https://github.com/sensu-plugins/sensu-plugins-mailer) project look for their configuration under `mailer`, `mailer-ses` and `mailer-mailgun` top-level keys, respectively.

> If it is necessary to add configuration in the top-level map of the JSON files in `conf.d/checks/`, then sensu::check should take a `config` property which is merged together with the `checks` top level key.

I think it's worth noting that this configuration convention isn't specific to check plugins. It can apply to handler plugins, mutator plugins and extensions of all sorts, be they check, filter, mutator or handler. With this in mind, I think instructing users of this module to provide custom configuration using `sensu::write_json` directly instead of adding a `config` property on `sensu::check` might make more sense.

**Comment by jeffmccune** [comment]
Working on this now, I'm going to proceed with the approach of adding a `config` property to the sensu_check type and provider, primarily because this retains the modeling of Sensu configuration as Puppet resources, e.g. sensu::check instead of sensu::write_json.  The implementation and spec test coverage for the provider will serve as an example for the other native types, which will reduce the time required to implement a `config` property for all types.

**Comment by jeffmccune** [comment]
@cwjohnston After spending a little time looking into a config property, I think you're suggestion of using sensu_write_json() is way better.  There are a bunch of edge cases around the merging of an arbitrary config map with all the other properties, especially the `custom` property which itself is an arbitrary map.  Adding `config` significantly increases complexity of the types, whereas refactoring the defined types to use `sensu_write_json()` should reduce the complexity located in the native types.  The puppet code will be a bit more complex, but this should be easier to maintain compared to native types over the long run.

I'm going to close the WIP related to the config property and switch over to refactoring the defined types to use sensu_write_json().

**Comment by jeffmccune** [comment]
Next steps on this are to get #785 merged, let it bake in the community, then remove `sensu_check_config`, replaced by the content parameter of sensu::check.

**Comment by ghoneycutt** [comment]
In order to preserve semver, this will wait until the module is redone for Sensu 2.
