### ISSUE TITLE
Sensu Enterprise HEAP_SIZE is not configurable

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-puppet#767]
## Expected Behavior

When using Sensu Enterprise, this module should manage the HEAP_SIZE environment variable defined in `/etc/default/sensu-enterprise`

## Current Behavior

This module does not expose a parameter for managing `HEAP_SIZE`

## Context

Attempting to manage the contents of `/etc/default/sensu-enterprise` or `/etc/default/sensu` outside of this module can lead to unnecessary service restarts.

## Possible Solution

Add a parameter to `sensu` class providing control over the `HEAP_SIZE` when the value of the `sensu_enterprise` parameter is `true`

**Comment by cwjohnston** [comment]
Note that it's equally reasonable to configure this environment variable via `/etc/default/sensu`, as it will also be evaluated when starting `sensu-enterprise`

**Comment by alvagante** [comment]
@cwjohnston please correct me if I'm wrong:
I'm going to add a heap_size param that, if defined, adds to /etc/default/sensu (or /etc/default/sensu-enterprise if used) the line:
HEAP_SIZE=<%= @heap_size %>
I suspect the value might not only be an Integer (ie 256M) so validation should be for a normal string.

Please confirm or correct me.

**Comment by cwjohnston** [comment]
@alvagante I believe you are correct, HEAP_SIZE should allow a string value so the suffix can indicate unit of measure.

FWIW, HEAP_SIZE has no effect on Sensu Core (sensu-server), only on Sensu Enterprise.

**Comment by alvagante** [comment]
@cwjohnston thanks for quick reply. The commit (blind code, still not tested on real vm) done modifies the file for both, as the same template is used.
If you want I can remove the changes in https://github.com/alvagante/sensu-puppet/commit/7f706f6d727be6abb46905ce44a51d6fc8e36f55#diff-1576180ba8964fff8d837b3256127ebc so that in sensu-core even if heap_size is set, it does not appear in /etc/default/sensu.
Alternatively I would add a note in the docs and leave the heap_size param in sensu::package as is. Eventually HEAP_SIZE might be used in the future also in sensu-core.

Any preference?

**Comment by ghoneycutt** [comment]
Prefer to keep it as a param in init.pp and just document that it is only for the enterprise software.

**Comment by alvagante** [comment]
@ghoneycutt so is the current implementation, even if it has a redundant parameter in sensu::package.
If you want I can remove sensu::package::heap_size, and relevant tests, otherwise https://github.com/sensu/sensu-puppet/pull/771 should be ready to merge

**Comment by ghoneycutt** [comment]
Released in v2.30.0
