### ISSUE TITLE
[puppetlabs/apt] Version bumping for apt module

### ISSUE THREAD

**Issue by SergK** [sensu/sensu-puppet#781]
## Description of problem

- Reproduced with  module version > v2.5.0
- Using sensu module with other third party modules failed because of dependency issue

I have a number of modules which have requirements on apt module, e.g (puppet-grafana, locp-cassandra):

```
{"name":"puppetlabs/apt","version_requirement":">= 2.0.0 < 3.0.0"},
```
that is why using requirements from sensu module breaks this dependecy since

```
    {
      "name": "puppetlabs/apt",
      "version_requirement": ">= 4.0.0 < 5.0.0"
},
```

So I wonder about this change https://github.com/sensu/sensu-puppet/commit/7179c92ae817e9557713a065724f453507f10914 
Can we have more information on this bump? And is it possible to revert it or at least decrease the lower bound

**Comment by ghoneycutt** [comment]
@SergK Thank for reporting this. It seems the issue is with your dependency tree and not with the dependencies within this module.

Supporting multiple major versions of a dependency is not something we are willing to do, as each major version can introduce breaking changes.

If you still want to use the older version and are having issues with `puppet module install`, suggest using a tool to manage your repos that does not do dependency checking such as https://github.com/bodepd/librarian-puppet-simple
