### ISSUE TITLE
CONFIG_FILE environment variable should be configurable

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-puppet#851]
## Description of problem

The value of `CONFIG_FILE` environment variable is not currently configurable via this module.

Both Sensu Core and Sensu Enterprise use the value of the `CONFIG_FILE` environment variable to set the `--config` flag when starting Sensu processes. This flag specifies a singular JSON config file, the content of which is deep merged with the contents of the directory specified by the `--config_dir` flag. The `CONFD_DIR` environment variable used to set the value of `--config_dir` flag is [already configurable via this module](https://github.com/sensu/sensu-puppet/blob/master/templates/sensu.erb#L16-L18).

The default `CONFIG_FILE` value is `/etc/sensu/config.json` (e.g. https://github.com/sensu/sensu-omnibus/blob/master/files/sensu-gem/bin/sensu-service#L46-L55)

**Comment by ghoneycutt** [comment]
I do not see `CONFIG_FILE` listed in #849 
Seems like that should be configurable in `/etc/default/sensu`, correct?

**Comment by cwjohnston** [comment]
@ghoneycutt yes, `CONFIG_FILE` is honored by both Sensu Core and Sensu Enterprise, so I believe `/etc/default/sensu` is the right place.

**Comment by alvagante** [comment]
@cwjohnston @ghoneycutt If you agree I'd add it with eventually all the others listed in #849.
Note that given the current code base this would require adding relevant parameters to the main class in init.pp, and at least packages.pp. There parameters would match environment variables like SENSU_CLIENT_SUBSCRIPTIONS, SENSU_TRANSPORT_NAME, RABBITMQ_URL, REDIS_URL which are already defined in other parameters.
In order to manage  CONFIG_FILE, the above environment variables, and anything that is used in /etc/default/sensu (and /etc/default/sensu-enterprise), I would introduce a single parameter, an hash of configuration settings, so that there will ne need in the future to introduce new variables to support new  settings for those files.
In order to preserve compatibilty with current parameters, I'd merge the user provided hash, in this new parameter (something like env_vars) with a default one, with settings based on the current parameters of the class.
I probably take more time describing than doing, anyway.
If you want I can prepare the code that implements this to give you and idea and then decide if to follow it. Scope is the configuration of /etc/default/sensu and /etc/default/sensu-enterprise and the relevant current and future parameters to manage them.

**Comment by ghoneycutt** [comment]
I like this approach though it will require a major version change if we change parameters.

**Comment by cwjohnston** [comment]
Please see my note in https://github.com/sensu/sensu-puppet/issues/849#issuecomment-347954806. I am not in favor of managing env vars that overlap with config already managed by JSON.

**Comment by alvagante** [comment]
@ghoneycutt actually we can reserve the existing parameters, eventually with a deprecation notice of the ones we want to get rid of.

@cwjohnston  as in the note of https://github.com/sensu/sensu-puppet/issues/849#issuecomment-347981469 we can use this hash based approach for the settings of environment variables  which refer to elements not present in the json configs.

Actually we can allow the user also to set variables like REDIS_URL if he really wanted them in /etc/default/sensu . SO we can achieve both compatibility with current params and full customisability from users, for any current or future setting.
going to prepare a sample pr (code only , tests later) to show you the idea, I'm quite sure you'll like it.

**Comment by alvagante** [comment]
@ghoneycutt #861 does the job and replaces #852 
@cwjohnston sorry for taking some much time on this, the alternative approach I tried earlier was not worth the effor.

**Comment by ghoneycutt** [comment]
Released in v2.43.0
